(function(){
  "use strict";
  var reduced=window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  var year=document.getElementById("year");if(year)year.textContent=new Date().getFullYear();
  var menuButton=document.getElementById("menu-button"),mobileNav=document.getElementById("mobile-nav");
  if(menuButton&&mobileNav){menuButton.addEventListener("click",function(){var open=mobileNav.classList.toggle("is-open");menuButton.setAttribute("aria-expanded",String(open));});mobileNav.querySelectorAll("a").forEach(function(a){a.addEventListener("click",function(){mobileNav.classList.remove("is-open");menuButton.setAttribute("aria-expanded","false");});});}

  var progress=document.getElementById("page-progress-fill");
  function updateProgress(){if(!progress)return;var max=document.documentElement.scrollHeight-window.innerHeight;progress.style.width=(max>0?window.scrollY/max*100:0)+"%";}
  window.addEventListener("scroll",updateProgress,{passive:true});updateProgress();

  var reveals=document.querySelectorAll(".reveal");
  if(reduced||!("IntersectionObserver" in window)){reveals.forEach(function(el){el.classList.add("is-visible");});}
  else{var ro=new IntersectionObserver(function(entries){entries.forEach(function(e){if(e.isIntersecting){e.target.classList.add("is-visible");ro.unobserve(e.target);}});},{threshold:.08,rootMargin:"0px 0px -25px 0px"});reveals.forEach(function(el){ro.observe(el);});}

  var focus=document.getElementById("focus-rotator");
  if(focus&&!reduced){var roles=["AI/ML engineering","RAG & LLM applications","backend-heavy AI systems","applied machine learning"],ri=0;setInterval(function(){focus.classList.add("is-changing");setTimeout(function(){ri=(ri+1)%roles.length;focus.textContent=roles[ri];focus.classList.remove("is-changing");},160);},2600);}

  document.querySelectorAll("[data-count-to]").forEach(function(el){var target=parseFloat(el.dataset.countTo),dec=parseInt(el.dataset.decimals||"0",10),suffix=el.dataset.suffix||"";if(reduced){el.textContent=target.toFixed(dec)+suffix;return;}var seen=false;var obs=new IntersectionObserver(function(es){es.forEach(function(e){if(!e.isIntersecting||seen)return;seen=true;var start=null,d=700;function tick(t){if(start===null)start=t;var p=Math.min((t-start)/d,1),v=target*(1-Math.pow(1-p,3));el.textContent=v.toFixed(dec)+suffix;if(p<1)requestAnimationFrame(tick);}requestAnimationFrame(tick);obs.disconnect();});},{threshold:.5});obs.observe(el);});

  var cards=Array.prototype.slice.call(document.querySelectorAll(".project-card"));
  cards.forEach(function(card){card.addEventListener("pointermove",function(e){var r=card.getBoundingClientRect();card.style.setProperty("--mx",((e.clientX-r.left)/r.width*100)+"%");card.style.setProperty("--my",((e.clientY-r.top)/r.height*100)+"%");});});

  var skillButtons=Array.prototype.slice.call(document.querySelectorAll("[data-skill]"));
  var filterStatus=document.getElementById("project-filter-status"),clearFilter=document.getElementById("clear-project-filter"),active=null;
  var aliases={
    "pytorch":["pytorch","ml","ai"],"scikit-learn":["scikit-learn","ml"],"pandas-numpy":["pandas-numpy","data","ml"],"langchain":["langchain","rag"],"llamaindex":["llamaindex","rag"],"rag":["rag"],"chromadb":["chromadb","rag"],"sentence-transformers":["sentence-transformers","embeddings","rag"],"groq":["groq","ai"],"prompt-engineering":["prompt-engineering","ai"],"feature-engineering":["feature-engineering","ml"],"hyperparameter-tuning":["hyperparameter-tuning","ml"],"evaluation":["evaluation","ai"],"testing":["testing"],"guardrails":["guardrails","ai"],"experimental-design":["experimental-design","research"],
    "python":["python"],"csharp":["csharp"],"fastapi":["fastapi"],"flask":["flask"],"aspnet":["aspnet"],"rest-apis":["rest-apis","backend"],
    "sql":["sql","data"],"postgresql":["postgresql","data"],"sql-server":["sql-server","data"],"mysql":["mysql","data"],"gcp":["gcp","data"],"bigquery":["bigquery","data"],"dataflow":["dataflow","data"],"etl":["etl","data"],"tableau":["tableau","data"],"power-bi":["power-bi","data"],"dax":["dax","data"],
    "react":["react","product"],"nextjs":["nextjs","product"],"flutter":["flutter","mobile"],"javascript":["javascript","product"],"typescript":["typescript","product"],"dart":["dart","mobile"],"html-css":["html-css","product"],"supabase":["supabase","product"],"firebase":["firebase","backend","product"],
    "git":["git"],"github":["github"],"cicd":["cicd"],"docker":["docker"],"agile":["agile"]
  };
  function clearSkillFilter(){if(active)active.classList.remove("is-active");active=null;cards.forEach(function(c){c.classList.remove("is-match","is-dim");});if(filterStatus)filterStatus.querySelector("span").textContent="Showing selected work";if(clearFilter)clearFilter.hidden=true;}
  function applySkill(button){var key=button.dataset.skill,list=aliases[key]||[key],matches=0;cards.forEach(function(c){var stack=(c.dataset.stack||"").toLowerCase().split(/\s+/),hit=list.some(function(a){return stack.indexOf(a)!==-1;});c.classList.toggle("is-match",hit);c.classList.toggle("is-dim",!hit);if(hit)matches++;});if(filterStatus)filterStatus.querySelector("span").textContent=matches?button.textContent.trim()+" → "+matches+" project"+(matches===1?"":"s"):button.textContent.trim()+" → not in this selected set";if(clearFilter)clearFilter.hidden=false;var ps=document.getElementById("projects");if(ps)ps.scrollIntoView({behavior:reduced?"auto":"smooth",block:"start"});}
  skillButtons.forEach(function(b){b.addEventListener("click",function(){if(active===b){clearSkillFilter();return;}if(active)active.classList.remove("is-active");active=b;b.classList.add("is-active");applySkill(b);});});if(clearFilter)clearFilter.addEventListener("click",clearSkillFilter);

  var jd=document.getElementById("jd-input"),analyze=document.getElementById("analyze-jd"),clearJd=document.getElementById("clear-jd"),empty=document.getElementById("matcher-empty"),results=document.getElementById("matcher-results"),scoreEl=document.getElementById("match-score"),ring=document.getElementById("score-ring"),label=document.getElementById("match-label"),summary=document.getElementById("match-summary"),matched=document.getElementById("matched-skills"),missing=document.getElementById("missing-skills"),evidence=document.getElementById("evidence-list"),brief=document.getElementById("recruiter-brief-text"),warning=document.getElementById("experience-warning"),copy=document.getElementById("copy-summary");
  var PROFILE_YEARS=1.5,lastSummary="";
  var map=[
    ["Python",["python"],"Python is used across production backend and AI/ML work."],["FastAPI",["fastapi","fast api"],"FastAPI appears in current middleware work and AI Learning Research."],["Flask",["flask"],"Mabros Couriers uses Flask for a live backend API."],["REST APIs",["rest api","restful","api development","apis"],"REST API design appears in both professional roles and project work."],["Docker",["docker","containerization","containers"],"Docker is used in current professional work and Mabros Couriers."],
    ["Git",["git","version control"],"Git is part of the engineering workflow and recent DataCamp coursework."],["GitHub",["github"],"GitHub is used for project source and collaboration workflows; GitHub Foundations was completed on DataCamp."],["CI/CD",["ci/cd","ci cd","continuous integration","continuous delivery","continuous deployment"],"CI/CD is part of the stated engineering workflow."],["Agile",["agile","scrum"],"Agile is part of the engineering practices stack."],
    ["SQL",["sql","relational database","relational databases"],"SQL and relational design appear in professional work and data projects."],["PostgreSQL",["postgresql","postgres"],"PostgreSQL is part of the database stack."],["MySQL",["mysql"],"MySQL is part of the database stack."],["SQL Server",["sql server","mssql"],"SQL Server is part of the database stack."],["GCP",["gcp","google cloud","google cloud platform"],"Google Cloud is part of the cloud/data stack."],["BigQuery",["bigquery","big query"],"BigQuery and BigQuery ML are part of the cloud/data stack."],["Dataflow",["dataflow"],"Dataflow is listed in the data engineering stack."],["ETL",["etl","data pipeline","data pipelines","data engineering"],"ETL pipelines are part of the data engineering capability set."],["Tableau",["tableau"],"A live Tableau sales dashboard is available on the work page."],["Power BI",["power bi","powerbi"],"Power BI is listed in the BI stack."],["DAX",["dax"],"DAX is listed in the BI stack."],
    ["PyTorch",["pytorch","torch"],"PyTorch is part of the ML stack."],["Scikit-learn",["scikit-learn","sklearn","scikit learn"],"The Bank Marketing project compares and tunes multiple Scikit-learn classifiers."],["Machine Learning",["machine learning","predictive modeling","classification model"],"The Bank Marketing project demonstrates model comparison, feature engineering, and tuning."],["Pandas / NumPy",["pandas","numpy"],"Pandas and NumPy are part of the ML/data stack."],["RAG",["retrieval augmented generation","retrieval-augmented generation","rag"],"Reflct and AI Growth Journal demonstrate retrieval-based AI application work."],["LangChain",["langchain"],"AI Growth Journal uses LangChain in its RAG pipeline."],["LlamaIndex",["llamaindex","llama index"],"Reflct uses LlamaIndex for retrieval."],["ChromaDB",["chromadb","chroma"],"AI Growth Journal uses ChromaDB in its retrieval stack."],["Embeddings",["embedding","embeddings","vector search","semantic search","sentence transformer"],"AI Growth Journal uses vector embeddings and semantic retrieval."],["Groq",["groq"],"Reflct uses Groq for LLM inference."],["LLM applications",["llm","large language model","generative ai","genai"],"AI Learning Research, Reflct, and AI Growth Journal demonstrate applied LLM system design."],["Prompt Engineering",["prompt engineering","prompt design","system prompt"],"AI Learning Research uses versioned prompts and explicit assistance constraints."],["AI Evaluation",["llm evaluation","ai evaluation","evaluation framework","evals","evaluation pipeline"],"AI Learning Research includes staged tasks, deterministic grading, controlled assistance, and research logging."],["Testing / Pytest",["pytest","unit testing","integration testing","automated tests","testing"],"AI Learning Research includes 15+ integrity and backend tests."],["AI Guardrails",["guardrails","ai guardrails","llm guardrails","ai safety","prompt constraints","safety controls"],"AI Learning Research enforces access rules, ownership, time windows, interaction caps, and constrained tutoring prompts."],["Experimental Design",["experimental design","controlled experiment","research design","a/b test","ab test"],"AI Learning Research uses controlled-AI and no-AI conditions with frozen provenance."],["Feature Engineering",["feature engineering"],"The Bank Marketing project includes feature engineering."],["Hyperparameter Tuning",["hyperparameter","gridsearchcv","grid search","model tuning"],"The Bank Marketing project uses model comparison and hyperparameter tuning."],
    ["React",["react.js","reactjs","react"],"Current professional work includes React.js features."],["Next.js",["next.js","nextjs"],"Reflct is a live application built with Next.js."],["Flutter",["flutter","dart"],"Current role includes Flutter ownership and Popal Eats is published on Google Play."],["JavaScript",["javascript","js"],"JavaScript is part of the product engineering stack."],["TypeScript",["typescript","ts"],"TypeScript is part of the product engineering stack."],["Supabase",["supabase"],"Reflct uses Supabase for persistent application data."],["Firebase",["firebase"],"Mabros Couriers uses Firebase in its backend stack."],["C#",["c#","c sharp","csharp",".net","dotnet"],"C#/.NET is part of the software engineering background."],["ASP.NET MVC",["asp.net","aspnet","mvc"],"ASP.NET MVC is part of the backend stack."]
  ];
  function norm(s){return " "+s.toLowerCase().replace(/[\n\r\t]+/g," ").replace(/[^a-z0-9+#./-]+/g," ").replace(/\s+/g," ").trim()+" ";}
  function hit(text,alias){var a=alias.toLowerCase();if(a.length<=3&&/^[a-z]+$/.test(a))return text.indexOf(" "+a+" ")!==-1;return text.indexOf(a)!==-1;}
  function requestedYears(raw){var ms=[].concat(Array.from(raw.matchAll(/(\d+(?:\.\d+)?)\s*\+?\s*(?:years?|yrs?)/gi))).map(function(m){return parseFloat(m[1]);}).filter(isFinite);return ms.length?Math.max.apply(null,ms):null;}
  function addTags(el,arr){el.innerHTML="";(arr.length?arr:["None recognized"]).forEach(function(x){var s=document.createElement("span");s.textContent=x;el.appendChild(s);});}
  function runMatcher(){if(!jd||!jd.value.trim())return;var raw=jd.value,text=norm(raw),recognized=[],hits=[],gaps=[];map.forEach(function(item){var found=item[1].some(function(a){return hit(text,a);});if(found){recognized.push(item[0]);hits.push(item);}});var explicitGaps=[["AWS",["aws","amazon web services"]],["Azure",["azure"]],["Kubernetes",["kubernetes","k8s"]],["TensorFlow",["tensorflow"]],["Spark",["apache spark","pyspark"]],["Kafka",["kafka"]],["Airflow",["airflow"]],["Redis",["redis"]],["MongoDB",["mongodb","mongo db"]]].filter(function(g){return g[1].some(function(a){return hit(text,a);});}).map(function(g){return g[0];});gaps=explicitGaps;
    var reqCount=recognized.length+gaps.length,score=reqCount?Math.round(recognized.length/reqCount*100):0;var years=requestedYears(raw);if(years&&years>PROFILE_YEARS)score=Math.max(0,score-8);var lab=score>=80?"Strong evidence overlap":score>=60?"Good evidence overlap":score>=40?"Partial evidence overlap":"Limited recognized overlap";
    var sum=reqCount?recognized.length+" recognized requirement"+(recognized.length===1?"":"s")+" matched portfolio evidence; "+gaps.length+" explicitly requested technolog"+(gaps.length===1?"y":"ies")+" are not currently shown.":"I could not identify enough requirements from the controlled skill set. Add the stack, tools, or engineering requirements for a more useful comparison.";
    var strongest=recognized.slice(0,6);var br=strongest.length?"Strongest overlap: "+strongest.join(", ")+". Evidence is concentrated in professional API/backend work plus AI Learning Research, Reflct, Mabros Couriers, and the ML/RAG projects.":"The JD does not yet contain enough recognized requirements to produce a useful brief.";if(gaps.length)br+=" Validate gaps: "+gaps.join(", ")+".";
    if(scoreEl)scoreEl.textContent=score+"%";if(ring)ring.style.setProperty("--score",score*3.6+"deg");if(label)label.textContent=lab;if(summary)summary.textContent=sum;if(brief)brief.textContent=br;addTags(matched,recognized);addTags(missing,gaps);if(evidence){evidence.innerHTML="";hits.slice(0,6).forEach(function(item){var li=document.createElement("li");li.textContent=item[2];evidence.appendChild(li);});}
    if(warning){if(years&&years>PROFILE_YEARS){warning.hidden=false;warning.textContent="Experience note: this JD appears to request about "+years+" years; the portfolio currently demonstrates about "+PROFILE_YEARS+"+ years of professional engineering experience.";}else warning.hidden=true;}
    lastSummary="Evidence overlap: "+score+"% — "+lab+". "+sum+" "+br;if(empty)empty.hidden=true;if(results)results.hidden=false;
  }
  if(analyze)analyze.addEventListener("click",runMatcher);if(jd)jd.addEventListener("keydown",function(e){if((e.ctrlKey||e.metaKey)&&e.key==="Enter")runMatcher();});if(clearJd)clearJd.addEventListener("click",function(){if(jd)jd.value="";if(results)results.hidden=true;if(empty)empty.hidden=false;});if(copy)copy.addEventListener("click",function(){if(!lastSummary)return;navigator.clipboard.writeText(lastSummary).then(function(){var old=copy.textContent;copy.textContent="Copied";setTimeout(function(){copy.textContent=old;},1000);}).catch(function(){});});

  var credentialDialog=document.getElementById("credential-dialog"),credentialImage=document.getElementById("credential-dialog-image"),credentialTitle=document.getElementById("credential-dialog-title"),credentialClose=document.getElementById("credential-dialog-close");
  function closeCredential(){if(credentialDialog&&credentialDialog.open)credentialDialog.close();}
  document.querySelectorAll("[data-credential-image]").forEach(function(b){b.addEventListener("click",function(){if(!credentialDialog||!credentialImage)return;credentialImage.src=b.dataset.credentialImage;credentialImage.alt=b.dataset.credentialTitle||"Credential preview";if(credentialTitle)credentialTitle.textContent=b.dataset.credentialTitle||"Credential preview";if(typeof credentialDialog.showModal==="function")credentialDialog.showModal();});});
  if(credentialClose)credentialClose.addEventListener("click",closeCredential);
  if(credentialDialog)credentialDialog.addEventListener("click",function(e){if(e.target===credentialDialog)closeCredential();});

  function openCaseFromHash(){if(!window.location.hash)return;var target=document.querySelector(window.location.hash);if(target&&target.tagName&&target.tagName.toLowerCase()==="details"){target.open=true;setTimeout(function(){target.scrollIntoView({behavior:reduced?"auto":"smooth",block:"start"});},30);}}
  window.addEventListener("hashchange",openCaseFromHash);openCaseFromHash();
})();
